# Generated by Django 3.1 on 2020-11-14 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccas', '0001_initial'),
        ('students', '0004_auto_20200911_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_status', models.CharField(choices=[('M', 'Member'), ('L', 'Leader')], max_length=1)),
                ('cca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cca_to_student', to='ccas.cca')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_to_cca', to='students.student')),
            ],
            options={
                'unique_together': {('cca', 'student')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='ccas',
            field=models.ManyToManyField(related_name='students', through='students.Membership', to='ccas.Cca'),
        ),
    ]
